import { Product, GroupDeal } from '../types'; 

// --- נתונים למסך הבית (Home) ---
  // --- נתונים למסך הבית (Home) ---
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Sony 65" 4K TV',
    slug: 'sony-65-tv',
    category_id: 1,
    description: 'Latest model with AI processor.',
    price_regular: 5500,
    price_group: 4200,
    discount_pct: 0.23,
    currency: 'ILS',
    image_url: 'https://placehold.co/600x400/png?text=Sony+TV',
    min_members: 50,
    active_group: {
      id: 'g1',
      product_id: 'p1',
      status: 'OPEN',
      joined_count: 42,
      target_members: 50,
      deadline: new Date(Date.now() + 86400000 * 2).toISOString(),
      progress_pct: 0.84,
    }
  },
  {
    id: 'p2',
    name: 'Dyson V15 Detect',
    slug: 'dyson-v15',
    category_id: 2,
    description: 'Powerful cordless vacuum.',
    price_regular: 3200,
    price_group: 2400,
    discount_pct: 0.25,
    currency: 'ILS',
    image_url: 'https://placehold.co/600x400/png?text=Dyson',
    min_members: 100,
    active_group: {
      id: 'g2',
      product_id: 'p2',
      status: 'OPEN',
      joined_count: 15,
      target_members: 100,
      deadline: new Date(Date.now() + 86400000 * 5).toISOString(),
      progress_pct: 0.15,
    }
  },
  {
    id: 'p3',
    name: 'Ninja Grill XL',
    slug: 'ninja-grill',
    category_id: 3,
    description: 'Indoor grill and air fryer.',
    price_regular: 1400,
    price_group: 950,
    discount_pct: 0.32,
    currency: 'ILS',
    image_url: 'https://placehold.co/600x400/png?text=Ninja',
    min_members: 200,
    active_group: {
      id: 'g3',
      product_id: 'p3',
      status: 'OPEN',
      joined_count: 180,
      target_members: 200,
      deadline: new Date(Date.now() + 86400000 * 1).toISOString(),
      progress_pct: 0.90,
    }
  },
  {
    id: 'p4',
    name: 'Apple AirPods Pro 2',
    slug: 'airpods-pro-2',
    category_id: 1,
    description: 'Active noise cancellation.',
    price_regular: 1100,
    price_group: 890,
    discount_pct: 0.19,
    currency: 'ILS',
    image_url: 'https://placehold.co/600x400/png?text=AirPods',
    min_members: 50,
    active_group: {
      id: 'g4',
      product_id: 'p4',
      status: 'OPEN',
      joined_count: 10,
      target_members: 50,
      deadline: new Date(Date.now() + 86400000 * 4).toISOString(),
      progress_pct: 0.20,
    }
  },
  {
    id: 'p5',
    name: 'Nespresso Vertuo',
    slug: 'nespresso-vertuo',
    category_id: 3,
    description: 'Coffee machine with capsules.',
    price_regular: 800,
    price_group: 499,
    discount_pct: 0.37,
    currency: 'ILS',
    image_url: 'https://placehold.co/600x400/png?text=Nespresso',
    min_members: 30,
    active_group: {
      id: 'g5',
      product_id: 'p5',
      status: 'OPEN',
      joined_count: 5,
      target_members: 30,
      deadline: new Date(Date.now() + 86400000 * 7).toISOString(),
      progress_pct: 0.16,
    }
  },
  {
    id: 'p6',
    name: 'Xiaomi Scooter 4',
    slug: 'xiaomi-scooter',
    category_id: 5,
    description: 'Electric scooter 35km range.',
    price_regular: 2200,
    price_group: 1750,
    discount_pct: 0.20,
    currency: 'ILS',
    image_url: 'https://placehold.co/600x400/png?text=Scooter',
    min_members: 20,
    active_group: {
      id: 'g6',
      product_id: 'p6',
      status: 'OPEN',
      joined_count: 19,
      target_members: 20,
      deadline: new Date(Date.now() + 86400000 * 0.5).toISOString(),
      progress_pct: 0.95,
    }
  }
];